### ISSUE TITLE
”by adding images with non-labeled fire objects as negative samples.“

### ISSUE THREAD

**Issue by liuliaocheng** [spacewalk01/yolov5-fire-detection#1]
”by adding images with non-labeled fire objects as negative samples.“
Can this approach improve the performance of the model? What is the reason?
thx~

**Comment by spacewalk01** [comment]
I will try to retrain the model by adding more negative samples and update my repo soon. You may refer this link about improving yolo performance here https://github.com/AlexeyAB/darknet (How to improve object detection part) .
