### ISSUE TITLE
send yolov5 model

### ISSUE THREAD

**Issue by PersianCoders** [spacewalk01/yolov5-fire-detection#2]
hello dear
could you upload or add your trained model to repo?
thanks a lot

**Comment by spacewalk01** [comment]
Hi, I will upload it tomorrow. Thanks

**Comment by spacewalk01** [comment]
Here is the pretrained model:
https://mega.nz/file/t8kgHZRD#cjlFhQu-GkVnsmayxqF98EHpbpC6J6b9fmOJJeDFZNc
