### ISSUE TITLE
Wrong Detection

### ISSUE THREAD

**Issue by PersianCoders** [spacewalk01/yolov5-fire-detection#3]
hello dear
when I run the model , sometimes detect wrong object(such as lights). how can I solve this problem?

![wrong](https://user-images.githubusercontent.com/23001051/157263638-867223b8-ebf1-459a-adc5-b2d87e3b8fa6.JPG)

do you have a better model?

**Comment by spacewalk01** [comment]
Not yet. I am trying to improve the model. When I get a better model, I will upload it. In general It is quite hard to distinguish between light and fire but you may consider training the model with more images with light and train it longer.

**Comment by PersianCoders** [comment]
Thank you for your reply.
Your work is very good

**Comment by Ashvith** [comment]
@spacewalk01 Interesting to see that you're going through the same problem as well. I tried with [this](https://www.kaggle.com/phylake1337/fire-dataset) datasets, but the model is of very poor quality. Using prerecorded videos makes the model perform decently (still poor detection, but able to avoid sun glares and lights). On using my laptop's webcam for the sake of curiosity, it tried to label exposure to sunlight as fire too.

**Comment by spacewalk01** [comment]
Thank you for sharing your experience. My thought is that there should be a vector space that differentiates two objects, sun/light vs fire. In terms of intensity of light, sun glare and fire lights are quite similar and hard to differentiate, but if we think of the occurrence of fire as time series data, we can model the movement of fire intensity/flare movement as a feature and possibly alleviate such misclassification problem.
